### ISSUE TITLE
Net::ReadTimeout  Exception while trying to upload through the URL method

### ISSUE THREAD

**Issue by srkgupta** [kraken-io/kraken-ruby#10]
Hi, 

I am uploading the images through the URL method provided by Kraken Ruby Gem. However, at times I get this exception and the upload operation fails. 

C:/Ruby21/lib/ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)                 
        from C:/Ruby21/lib/ruby/2.1.0/net/protocol.rb:152:in`rbuf_fill'  
        from C:/Ruby21/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'                                                   
        from C:/Ruby21/lib/ruby/2.1.0/net/protocol.rb:144:in`readline'  
        from C:/Ruby21/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'                                        
        from C:/Ruby21/lib/ruby/2.1.0/net/http/response.rb:28:in`read_new'  
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'                                     
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:1405:in`catch'  
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'                                              
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:1378:in`request'  
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:1371:in `block in request'                                               
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:853:in`start'  
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:1369:in `request'                                                        
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/httparty-0.13.7/lib/httparty/request.rb:117:in`perform'  
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'                   
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:492:in`post'  
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/kraken-io-0.1.3/lib/kraken-io.rb:39:in `block in url'                      
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/kraken-io-0.1.3/lib/kraken-io.rb:67:in`call_kraken'  
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/kraken-io-0.1.3/lib/kraken-io.rb:38:in `url'

**Comment by leadingproperties** [comment]
+1
